{
 "title": "Alarms",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Today's alarms",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(*) from alarms where DATE(created_at) = DATE(now())"
    }
   ]
  },
  {
   "title": "Today's number of alarms per sensor",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "Select sensor as \"Sensor name\", count(data) as \"Number of alarms\" from alarms where DATE(created_at) = DATE(now()) group by sensor"
    }
   ]
  },
  {
   "title": "Past alarms",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sensor as \"Sensor name\",\r\n  data as \"Sensor measurement\",\r\n  created_at as \"Measruement time\"\r\nFROM\r\n  alarms"
    }
   ]
  }
 ]
}