{
 "title": "Draw wires",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "North Face Out - Main Vertical Tensile Fault.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (-(((data+22.455)/0.0997)-224.98) - (-(((first_value(data) over (ORDER BY created_at ASC) +22.455)/0.0997)-224.98))) as \"North Face Out - Main Vertical Tensile Fault\", extract(EPOCH from created_at) as time FROM sensor_ds06_volts ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "North Face Out - Main Diagonal Fault.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ((((data+22.451)/0.0998)-224.98) - (((first_value(data) over (ORDER BY created_at ASC) +22.451)/0.0998)-224.98)) as \"North Face Out - Main Diagonal Fault\", extract(EPOCH from created_at) as time FROM sensor_ds22_volts ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "South Face Out - Main Vertical Tensile Fault.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (((data+22.498)/0.1)-224.98 - (-(((first_value(data) over (ORDER BY created_at ASC) +22.498)/0.1)-224.98))) as \"South Face Out - Main Vertical Tensile Fault\", extract(EPOCH from created_at) as time FROM sensor_ds11_volts ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "North Face Inside - Transverse Fault in box roof.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (((data+22.485)/0.0999)-224.98 - (-(((first_value(data) over (ORDER BY created_at ASC) +22.485)/0.0999)-224.98))) as \"North Face Inside - Transverse Fault in box roof\", extract(EPOCH from created_at) as time FROM sensor_ds21_volts ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "North Face Inside - Diagonal Fault.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (((data+22.464)/0.0997)-224.98 - (-(((first_value(data) over (ORDER BY created_at ASC) +22.464)/0.0997)-224.98))) as \"North Face Inside - Diagonal Fault\", extract(EPOCH from created_at) as time FROM sensor_ds23_volts ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "South Face Out - Diagonal Fault.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (((data+22.456)/0.0998)-224.98 - (((first_value(data) over (ORDER BY created_at ASC) +22.456)/0.0998)-224.98)) as \"South Face Out - Diagonal Fault\", extract(EPOCH from created_at) as time FROM sensor_ds20_volts ORDER BY created_at ASC"
    }
   ]
  }
 ]
}