{
 "title": "Draw wires trend analysis",
 "time": { "from": "now-10d", "to": "now" },
 "panels": [
  {
   "title": "North Face Out - Main Vertical Tensile Fault Trend.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (-(((data+22.455)/0.0997)-224.98) ) as \"North Face Out - Main Vertical Tensile Fault\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_ds06_volts\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "North Face Out - Main Diagonal Fault Trend.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ((((data+22.451)/0.0998)-224.98) ) as \"North Face Out - Main Diagonal Fault\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_ds22_volts\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "South Face Out - Main Vertical Tensile Fault Trend.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT (-(((data+22.455)/0.0997)-224.98) ) as \"South Face Out - Main Vertical Tensile Fault\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_ds11_volts\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "North Face Inside - Transverse Fault in box roof Trend.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT (((data+22.485)/0.0999)-224.98) as \"North Face Inside - Transverse Fault in box roof.\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_ds21_volts\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "North Face Inside - Diagonal Fault Trend.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT (((data+22.464)/0.0997)-224.98 ) as \"North Face Inside - Diagonal Fault\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_ds23_volts\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "South Face Out - Diagonal Fault Trend.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT (((data+22.456)/0.0998)-224.98 ) as \"South Face Out - Diagonal Fault\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_ds20_volts\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  }
 ]
}