{
 "title": "Vibrating wires",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "North Out VW10_1 to the beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_1 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw101_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "North Out VW10_2 away from the beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_2 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw102_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "South Out VW25_1 to beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_1 to beam\", extract(EPOCH from created_at) as time FROM sensor_vw251_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "South Mesa VW25_3 to the beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Mesa VW25_3 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw253_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "North Mesa VW10_3 to the beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Mesa VW10_3 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw103_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "North Mesa VW10_4 away from the beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Mesa VW10_4 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw104_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "South Out VW25_2 away from the beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_2 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw252_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "South Mesa VW25_4 away from the beam.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Mesa VW25_4 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw254_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_1 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw101_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_2 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw102_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Mesa VW10_3 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw103_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Mesa VW10_4 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw104_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_1 to beam\", extract(EPOCH from created_at) as time FROM sensor_vw251_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_2 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw252_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Mesa VW25_3 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw253_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Mesa VW25_4 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw254_hz ORDER BY created_at ASC"
    }
   ]
  }
 ]
}