{
 "title": "Vibrating wires total",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "South torque tension.",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Νότια Έξω VW25_1 προς τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw251_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Νότια Έξω VW25_2 μακρία από τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw252_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Νότια Μέσα VW25_3 προς τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw253_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Νότια Μέσα VW25_4 μακρία από τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw254_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "North torque tension.",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Βόρεια Έξω VW10_1 προς τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw101_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Βόρεια Έξω VW10_2 μακρία από τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw102_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Βόρεια Μέσα VW10_3 προς τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw103_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"Βόρεια Μέσα VW10_4 μακρία από τη δοκό\", extract(EPOCH from created_at) as time FROM sensor_vw104_hz ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "Total torque tension.",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_1 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw101_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_2 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw102_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Inside VW10_3 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw103_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Inside VW10_4 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw104_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_1 to beam\", extract(EPOCH from created_at) as time FROM sensor_vw251_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_2 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw252_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Inside VW25_3 to the beam\", extract(EPOCH from created_at) as time FROM sensor_vw253_hz ORDER BY created_at ASC"
    },
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((first_value(data) over (ORDER BY created_at ASC)/1000-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Inside VW25_4 away from the beam\", extract(EPOCH from created_at) as time FROM sensor_vw254_hz ORDER BY created_at ASC"
    }
   ]
  }
 ]
}