{
 "title": "Vibrating wires trend analysis",
 "time": { "from": "now-10d", "to": "now" },
 "panels": [
  {
   "title": "North Out VW10_1 to the beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_1 to the beam\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw101_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "North Out VW10_2 away from the beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"North Out VW10_2 away from the beam Trend\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw102_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "North Mesa VW10_3 to the beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0))as \"North Mesa VW10_3 to the beam\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw103_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "North Mesa VW10_4 away from the beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0))  as \"North Mesa VW10_4 away from the beam\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw104_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "South Out VW25_1 to beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_1 to beam\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw251_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "South Out VW25_2 away from the beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Out VW25_2 away from the beam\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw252_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "South Mesa VW25_3 to the beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Mesa VW25_3 to the beam.\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw253_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "South Mesa VW25_4 away from the beam Trend.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT (4508/NULLIF((3920*(-3920*((-data*data/1000)/10000000000)*198000*1734/9810)),0)) as \"South Mesa VW25_4 away from the beam\", date_trunc('day', created_at) FROM (\r\n  SELECT *, \r\n    ROW_NUMBER() OVER (PARTITION BY date_trunc('day', created_at) \r\n        ORDER BY data DESC) AS _rn\r\n  FROM public.sensor_vw254_hz\r\n) AS _max\r\nWHERE _rn = 1\r\nORDER BY created_at;"
    }
   ]
  }
 ]
}